# Generated by Django 2.2.7 on 2019-11-22 20:06

from django.db import migrations, models  # pragma: no cover
import django.db.models.deletion  # pragma: no cover


class Migration(migrations.Migration):  # pragma: no cover

    initial = True  # pragma: no cover

    dependencies = [  # pragma: no cover
    ]

    operations = [  # pragma: no cover
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_type', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('validity', models.DateField()),
                ('amount_bags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=150)),
                ('cafes_types', models.CharField(max_length=100)),
                ('quantity_bags_available', models.IntegerField()),
                ('stock_capability', models.IntegerField()),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Harvest')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.ManyToManyField(to='api.Stock')),
            ],
        ),
    ]
